apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/francopocatino/gke-platform
    targetRevision: main
    path: gitops/hello-api/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m
